--- 
 - name: Clone dotfiles to home directory
   ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "~/dotfiles"

 - name: Stow dotfiles
   shell: |
    cd ~/dotfiles
    git pull
    stow .

