--- 
 - name: Clone dotfiles to home directory
   ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "~/dotfiles"
   tags: initial
   register: cloned

 - name: Inital dotfiles
   # Sets up the links with --adopt, then changes with git restore, so all ends up identical to git
   shell: |
    cd ~/dotfiles
    git pull
    stow --adopt .
    git restore .
   tags: 
    - update
    - initial
   when: cloned
