--- 
 - name: Update dotfiles
   # Sets up the links with --adopt, then changes with git restore, so all ends up identical to git
   shell: |
    cd ~/dotfiles
    git pull
    stow --adopt .
    git restore .
